name: release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version: 1.19

      - run: make build
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/blast
          tag_name: ${{ github.event.release.tag_name }}
